package undo_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/Deln0r/ygo/internal/block"
	"github.com/Deln0r/ygo/internal/doc"
	"github.com/Deln0r/ygo/internal/types"
	"github.com/Deln0r/ygo/internal/undo"
)

// undoFixtureFile mirrors testdata/undo-fixtures.json, generated by
// testdata/gen/gen-undo.mjs from yjs@13.6.31's UndoManager.
type undoFixtureFile struct {
	Generator string             `json:"generator"`
	Scenarios []undoFixtureScene `json:"scenarios"`
}

type undoFixtureScene struct {
	Description string      `json:"description"`
	Kind        string      `json:"kind"`
	Root        string      `json:"root"`
	Expected    interface{} `json:"expected"`
}

// runByDescription executes the Go-side equivalent of each named yjs
// scenario and returns the final state in the same JSON-comparable
// shape as the fixture's Expected.
//
// The scenario logic is duplicated from gen-undo.mjs on purpose: there
// is no shared op-encoding, so the fixture only carries the reference
// end-state yjs arrived at, and we assert ygo lands on the same place.
func runByDescription(t *testing.T, desc string) interface{} {
	t.Helper()
	d := doc.NewDoc()

	switch desc {
	case "map set then undo":
		m := types.NewMap(d.Branch("m"))
		um := undo.NewUndoManager(d, []*block.Branch{m.Branch()}, undo.Options{CaptureTimeout: -1})
		defer um.Close()
		setMap(d, m, "theme", "dark")
		um.Undo()
		return mapState(m)

	case "map set then undo then redo":
		m := types.NewMap(d.Branch("m"))
		um := undo.NewUndoManager(d, []*block.Branch{m.Branch()}, undo.Options{CaptureTimeout: -1})
		defer um.Close()
		setMap(d, m, "theme", "dark")
		um.Undo()
		um.Redo()
		return mapState(m)

	case "map overwrite then undo reverts to first":
		m := types.NewMap(d.Branch("m"))
		um := undo.NewUndoManager(d, []*block.Branch{m.Branch()}, undo.Options{CaptureTimeout: -1})
		defer um.Close()
		setMap(d, m, "k", "first")
		setMap(d, m, "k", "second")
		um.Undo()
		return mapState(m)

	case "array insert then undo then redo":
		a := types.NewArray(d.Branch("a"))
		um := undo.NewUndoManager(d, []*block.Branch{a.Branch()}, undo.Options{CaptureTimeout: -1})
		defer um.Close()
		insertArray(d, a, 0, "x")
		um.Undo()
		um.Redo()
		return a.ToSlice()

	case "array delete then undo restores":
		a := types.NewArray(d.Branch("a"))
		um := undo.NewUndoManager(d, []*block.Branch{a.Branch()}, undo.Options{CaptureTimeout: -1})
		defer um.Close()
		insertArray(d, a, 0, "a")
		insertArray(d, a, 1, "b")
		deleteArray(d, a, 0, 1)
		um.Undo()
		return a.ToSlice()

	case "text insert then undo":
		x := types.NewText(d.Branch("t"))
		um := undo.NewUndoManager(d, []*block.Branch{x.Branch()}, undo.Options{CaptureTimeout: -1})
		defer um.Close()
		insertText(d, x, 0, "hello")
		um.Undo()
		return x.String()

	case "text delete then undo restores":
		x := types.NewText(d.Branch("t"))
		um := undo.NewUndoManager(d, []*block.Branch{x.Branch()}, undo.Options{CaptureTimeout: -1})
		defer um.Close()
		insertText(d, x, 0, "hello world")
		deleteText(d, x, 5, 6)
		um.Undo()
		return x.String()
	}

	t.Fatalf("no Go scenario for %q", desc)
	return nil
}

func setMap(d *doc.Doc, m *types.Map, k string, v any) {
	txn := d.WriteTxn()
	m.Set(txn, k, v)
	txn.Commit()
}

func insertArray(d *doc.Doc, a *types.Array, idx uint64, v any) {
	txn := d.WriteTxn()
	a.Insert(txn, idx, v)
	txn.Commit()
}

func deleteArray(d *doc.Doc, a *types.Array, idx, n uint64) {
	txn := d.WriteTxn()
	a.Delete(txn, idx, n)
	txn.Commit()
}

func insertText(d *doc.Doc, x *types.Text, idx uint64, s string) {
	txn := d.WriteTxn()
	_ = x.Insert(txn, idx, s)
	txn.Commit()
}

func deleteText(d *doc.Doc, x *types.Text, idx, n uint64) {
	txn := d.WriteTxn()
	_ = x.Delete(txn, idx, n)
	txn.Commit()
}

func mapState(m *types.Map) map[string]any {
	out := map[string]any{}
	m.Range(func(k string, v any) bool {
		out[k] = v
		return true
	})
	return out
}

// TestUndoFixtures_CrossLanguage replays each yjs UndoManager scenario
// through ygo and asserts identical end state.
func TestUndoFixtures_CrossLanguage(t *testing.T) {
	path := filepath.Join("..", "..", "testdata", "undo-fixtures.json")
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			t.Skip("testdata/undo-fixtures.json not present; run testdata/gen/gen-undo.mjs")
		}
		t.Fatalf("read fixture: %v", err)
	}
	var ff undoFixtureFile
	if err := json.Unmarshal(data, &ff); err != nil {
		t.Fatalf("unmarshal fixture: %v", err)
	}
	if len(ff.Scenarios) == 0 {
		t.Fatal("fixture file has no scenarios")
	}

	for _, sc := range ff.Scenarios {
		t.Run(sc.Description, func(t *testing.T) {
			got := runByDescription(t, sc.Description)
			if !undoStateEqual(got, sc.Expected) {
				t.Errorf("state mismatch\n got: %#v\nwant: %#v", got, sc.Expected)
			}
		})
	}
}

// undoStateEqual compares Go state against the JSON-decoded fixture,
// normalising for the usual JSON quirks (numbers as float64, etc.).
func undoStateEqual(got, want any) bool {
	switch w := want.(type) {
	case string:
		g, ok := got.(string)
		return ok && g == w
	case map[string]interface{}:
		g, ok := got.(map[string]any)
		if !ok || len(g) != len(w) {
			return false
		}
		for k, wv := range w {
			if !undoScalarEqual(g[k], wv) {
				return false
			}
		}
		return true
	case []interface{}:
		g, ok := got.([]any)
		if !ok || len(g) != len(w) {
			return false
		}
		for i := range w {
			if !undoScalarEqual(g[i], w[i]) {
				return false
			}
		}
		return true
	}
	return reflect.DeepEqual(got, want)
}

func undoScalarEqual(g, w any) bool {
	if gs, ok := g.(string); ok {
		ws, ok := w.(string)
		return ok && gs == ws
	}
	return reflect.DeepEqual(g, w)
}
